services:
  digital-latin-streamlit-ui-chatapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: digital-latin-streamlit-ui-chatapi
    command: ["bash", "./entrypoint.sh"]
    ports:
      - "8502:8502"
    volumes:
      - ./app:/app
    environment:
    # These environment variables are used to configure the Streamlit app and its dependencies.
      - SESSION_DB_BACKEND=${SESSION_DB_BACKEND}
      - WAIT_FOR_POSTGRES=false
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - SKIP_DB=${SKIP_DB}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_ALLOWED_MODELS=${GOOGLE_ALLOWED_MODELS}
      - GOOGLE_API_BASE_URL=${GOOGLE_API_BASE_URL}
      - FLOW_API_URL=${FLOW_API_URL}
      - AUTH_USER_1=${AUTH_USER_1}
      - AUTH_PASSWORD_1=${AUTH_PASSWORD_1}
      - AUTH_USER_2=${AUTH_USER_2}
      - AUTH_PASSWORD_2=${AUTH_PASSWORD_2}
      - AUTH_USER_3=${AUTH_USER_3}
      - AUTH_PASSWORD_3=${AUTH_PASSWORD_3}
