# syntax=docker/dockerfile:1
FROM docker.io/continuumio/miniconda3:latest

WORKDIR /app

# gcc is for build psutil in MacOS
RUN apt-get update && apt-get install -y runit gcc

COPY requirements.txt .

RUN conda create -n promptflow-serve python=3.9.16 pip=23.0.1 -q -y && \
    conda run -n promptflow-serve \
    pip install promptflow==1.18.1 \
    promptflow-tools && \
    conda run -n promptflow-serve pip install -r requirements.txt && \
    conda run -n promptflow-serve pip install gunicorn==22.0.0 && \
    conda run -n promptflow-serve pip install 'uvicorn>=0.27.0,<1.0.0' && \
    conda run -n promptflow-serve pip cache purge && \
    conda clean -a -y

RUN echo "import os" | cat - /opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/core/_serving/v1/blueprint/static_web_blueprint.py > temp && \
mv temp /opt/conda/envs/promptflow-serve/lib/python3.9/site-packages/promptflow/core/_serving/v1/blueprint/static_web_blueprint.py

COPY . .

# The following line is to make sure that the python path is set correctly and includes the digital_latin_flows and _connections_manager_ directories.
ENV PYTHONPATH='${PYTHONPATH}:/app'
RUN echo "PYTHONPATH is: $PYTHONPATH"

EXPOSE 8080

# reset runsvdir
RUN rm -rf /var/runit
COPY runit /var/runit
# grant permission
RUN chmod -R +x /var/runit

RUN chmod +x ./start.sh

CMD ["bash", "./start.sh"]
