services:
  digital-latin-streamlit-ui-chatapi:
    build: .
    container_name: digital-latin-streamlit-ui-chatapi
    command: streamlit run src/core/streamlit_ui_chatapi.py --server.port=8502 --server.address=0.0.0.0
    ports:
      - "8502:8502"
    volumes:
      - ./:/app
    environment:
      - SESSION_DB_BACKEND=${SESSION_DB_BACKEND}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
    depends_on:
      - digital-latin-postgres

  digital-latin-postgres:
    image: postgres:16
    container_name: digital-latin-postgres
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
